### ISSUE TITLE
error with skript-gui 1.3

### ISSUE THREAD

**Issue by juzijun233** [Lotzyprod/Skcrew#4]
```
 null
org.bukkit.command.CommandException: Unhandled exception executing command 'recaptchat' in plugin Skript v2.6.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2344) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2155) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2136) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1421) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1399) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1310) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: ch/njol/skript/lang/Expression
        at io.github.apickledwalrus.skriptgui.elements.expressions.ExprVirtualInventory.get(ExprVirtualInventory.java:87) ~[!Skript-Addon-skript-gui-1.3.jar:?]
        at io.github.apickledwalrus.skriptgui.elements.expressions.ExprVirtualInventory.get(ExprVirtualInventory.java:19) ~[!Skript-Addon-skript-gui-1.3.jar:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99) ~[!!!Skript[2.6.3].jar:?]
        at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:57) ~[!!!Skript[2.6.3].jar:?]
        at com.lotzy.skcrew.skriptgui.elements.sections.SecCreateGUI.walk(SecCreateGUI.java:81) ~[!Skript-Addon-Skcrew[1.5].jar:?]
        at ch.njol.skript.lang.EffectSectionEffect.walk(EffectSectionEffect.java:44) ~[!!!Skript[2.6.3].jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[!!!Skript[2.6.3].jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[!!!Skript[2.6.3].jar:?]
        at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85) ~[!!!Skript[2.6.3].jar:?]
        at ch.njol.skript.lang.function.Function.execute(Function.java:129) ~[!!!Skript[2.6.3].jar:?]
        at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:288) ~[!!!Skript[2.6.3].jar:?]
        at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52) ~[!!!Skript[2.6.3].jar:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[!!!Skript[2.6.3].jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[!!!Skript[2.6.3].jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[!!!Skript[2.6.3].jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[!!!Skript[2.6.3].jar:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:286) ~[!!!Skript[2.6.3].jar:?]
        at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:251) ~[!!!Skript[2.6.3].jar:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:256) ~[!!!Skript[2.6.3].jar:?]
        at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:195) ~[!!!Skript[2.6.3].jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Purpur-1428]
        ... 21 more
>
```

```
 Server Version: git-Purpur-1428 (MC: 1.17.1)
[23:52:22 INFO]: [Skript] Skript Version: 2.6.3
[23:52:22 INFO]: [Skript] Installed Skript Addons:
[23:52:22 INFO]: [Skript]  - Skellett v2.0.7 (https://forums.skunity.com/resources/skellett.24/)
[23:52:22 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[23:52:22 INFO]: [Skript]  - SkWaze v3.0.7
[23:52:22 INFO]: [Skript]  - skript-yaml v1.4
[23:52:22 INFO]: [Skript]  - MongoSK v2.3.0 (https://github.com/Romitou/MongoSK)
[23:52:22 INFO]: [Skript]  - SkBee v1.16.2 (https://github.com/ShaneBeee/SkBee)
[23:52:22 INFO]: [Skript]  - skScraft v1.5
[23:52:22 INFO]: [Skript]  - Skcrew v1.4 (https://github.com/LotzyProd/Skcrew)
[23:52:22 INFO]: [Skript]  - RediSkript v1.3.6-SNAPSHOT
[23:52:22 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[23:52:22 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[23:52:22 INFO]: [Skript]  - WebSK v1.2.1
[23:52:22 INFO]: [Skript]  - Diskuise v0.3 (https://github.com/UnderscoreTud/diskuise)
[23:52:22 INFO]: [Skript]  - skript-db v1.3.6
[23:52:22 INFO]: [Skript]  - Reqn v1.2.5
[23:52:22 INFO]: [Skript]  - SkriptJSON v1.0.0
[23:52:22 INFO]: [Skript]  - WebSKT v1.0-BETA.2 (tlatoani.us/webskt)
[23:52:22 INFO]: [Skript] Installed dependencies:
[23:52:22 INFO]: [Skript]  - Vault v1.7.3-b131
[23:52:22 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

**Comment by Lotzyprod** [comment]
Disable skript-gui, skript-db in Skcrew config, its included in Skcrew
Or remove Skript-gui and skript-db addons
